version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.20.3
    restart: always
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "test"
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
